[build]
  base = "/"
  publish = "frontend/build"
  command = "npm install && npm install --prefix frontend && npm run build --prefix frontend"

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/lambda/api/:splat"
